const languages = {
  "Deutsch": {
    statusLeft: "Punkte",
    statusMiddle: "Test",
    statusRight: "Münzen",
    title: "Vokabenteuer",
    description: "Ein Vokabeltrainer mit Gamification für Japanisch",
    menuButton1: "Training",
    menuButton2: "Abenteuer",
    menuButton3: "Einstellungen",
    training: "Training",
    adventure: "Abenteuer",
    difficulty: "Schwierigkeitsgrad",
    difficulty1: "Leicht",
    difficulty2: "Mittel",
    difficulty3: "Schwer",
    custom: "Eigene Anzahl",
    all: "Alles",
    selectionButton1: "Start",
    selectionButton2: "Zurück",
    words: 'Wörter',
    romajiLabel: "Romaji",
    kanaLabel: "Kana",
    trainingButton1: "Abbrechen",
    trainingButton2: 'Zurück',
    trainingButton3: 'Nächste',
    trainingButton4: 'Menü',
    trainingFinished: "Jetzt solltest du ein Abenteuer starten!",
    titleSettings: "Einstellungen",
    design1: "Hell",
    design2: "Dunkel",
    design3: "Slate",
    design4: "Solar",
    settingsButton1: "Anwenden",
    settingsButton2: "Zurück"
  },
  "English": {
    statusLeft: "Points",
    statusMiddle: "Test",
    statusRight: "Coins",
    title: "Vocadventure",
    description: "A vocabulary trainer with gamification for learning japanese",
    menuButton1: "Training",
    menuButton2: "Adventure",
    menuButton3: "Settings",
    training: "Training",
    adventure: "Adventure",
    difficulty: "Difficulty",
    difficulty1: "Easy",
    difficulty2: "Medium",
    difficulty3: "Hard",
    custom: "Custom number",
    all: "All",
    selectionButton1: "Start",
    selectionButton2: "Back",
    words: 'Words',
    romajiLabel: "Romaji",
    kanaLabel: "Kana",
    trainingButton1: 'Abort',
    trainingButton2: 'Back',
    trainingButton3: 'Next',
    trainingButton4: 'Menu',
    trainingFinished: "Now you should start an adventure!",
    titleSettings: "Settings",
    design1: "Light",
    design2: "Dark",
    design3: "Slate",
    design4: "Solar",
    settingsButton1: "Apply",
    settingsButton2: "Back"
  }
};