const languages = {
  "Deutsch": {
    statusLeft: "Punkte",
    statusMiddle: "Test",
    statusRight: "Münzen",
    title: "Vokabenteuer",
    description: "Ein Vokabeltrainer mit Gamification für Japanisch",
    menuButton1: "Training",
    menuButton2: "Abenteuer",
    menuButton3: "Item Laden",
    menuButton4: "Einstellungen",
    training: "Training",
    adventure: "Abenteuer",
    difficulty: "Schwierigkeitsgrad",
    difficulty1: "Leicht",
    difficulty2: "Mittel",
    difficulty3: "Schwer",
    custom: "Eigene Anzahl",
    all: "Alles",
    selectionButton1: "Start",
    selectionButton2: "Zurück",
    words: "Wörter",
    romajiLabel: "Romaji",
    kanaLabel: "Kana",
    trainingButton1: "Stop",
    trainingButton2: "Zurück",
    trainingButton3: "Nächste",
    trainingButton4: "Menü",
    trainingFinished: "Jetzt solltest du ein Abenteuer starten!",
    hiragana: "Hiragana",
    katakana: "Katakana",
    kanji: "Kanji",
    adventureButton1: "Stop",
    adventureButton2: "Gegenstände",
    adventureButton3: "Lösung",
    adventureButton4: "Bestätigen",
    adventureButton5: "Nächste",
    adventureButton6: "Ende",
    appletree: "Möchtest du Holz von diesem Baum mithilfe einer Axt sammeln?",
    actionButton1: "Ja",
    actionButton2: "Nein",
    shop: "Item Laden",
    wood: "Holz",
    stone: "Stein",
    ironOre: "Eisenerz",
    fish: "Fisch",
    worm: "Wurm",
    apple: "Apfel",
    shovel: "Schaufel",
    axe: "Axt",
    fishingRod: "Angel",
    string: "Faden",
    cobwebs: "Spinnweben",
    pickaxe: "Spitzhacke",
    shopButton1: "Menü",
    shopButton2: "Suche",
    shopButton3: "Inventar",
    shopButton4: "Zurück",
    inventory: "Inventar",
    titleDetails: "Details",
    materials: "Materialien",
    own: "Eigene",
    needed: "Benötigt",
    detailsButton1: "Zurück",
    detailsButton2: "Kaufen",
    titleSettings: "Einstellungen",
    design1: "Dunkel",
    design2: "Hell",
    design3: "Slate",
    design4: "Solar",
    small: "Klein",
    normal: "Normal",
    medium: "Mittel",
    large: "Groß",
    settingsButton1: "Anwenden",
    settingsButton2: "Zurück",
    empty: "Leer",
    confirmButton1: "Zurück",
    confirmButton2: "Bestätigen",
    clearData: "Daten löschen"
  },
  "English": {
    statusLeft: "Points",
    statusMiddle: "Test",
    statusRight: "Coins",
    title: "Vocadventure",
    description: "A vocabulary trainer with gamification for learning japanese",
    menuButton1: "Training",
    menuButton2: "Adventure",
    menuButton3: "Item Shop",
    menuButton4: "Settings",
    training: "Training",
    adventure: "Adventure",
    difficulty: "Difficulty",
    difficulty1: "Easy",
    difficulty2: "Medium",
    difficulty3: "Hard",
    custom: "Custom number",
    all: "All",
    selectionButton1: "Start",
    selectionButton2: "Back",
    words: "Words",
    romajiLabel: "Romaji",
    kanaLabel: "Kana",
    trainingButton1: "Stop",
    trainingButton2: "Back",
    trainingButton3: "Next",
    trainingButton4: "Menu",
    trainingFinished: "Now you should start an adventure!",
    hiragana: "Hiragana",
    katakana: "Katakana",
    kanji: "Kanji",
    adventureButton1: "Stop",
    adventureButton2: "Items",
    adventureButton3: "Solution",
    adventureButton4: "Confirm",
    adventureButton5: "Next",
    adventureButton6: "End",
    appletree: "Do you want to collect wood from this tree using an axe?",
    actionButton1: "Yes",
    actionButton2: "No",
    shop: "Item Shop",
    wood: "Wood",
    stone: "Stone",
    ironOre: "Iron Ore",
    fish: "Fish",
    worm: "Worm",
    apple: "Apple",
    shovel: "Shovel",
    axe: "Axe",
    fishingRod: "Fishing Rod",
    string: "String",
    cobwebs: "Cobwebs",
    pickaxe: "Pickaxe",
    shopButton1: "Menu",
    shopButton2: "Search",
    shopButton3: "Inventory",
    shopButton4: "Back",
    inventory: "Inventory",
    titleDetails: "Details",
    materials: "Materials",
    own: "Own",
    needed: "Needed",
    detailsButton1: "Back",
    detailsButton2: "Buy",
    titleSettings: "Settings",
    design1: "Dark",
    design2: "Light",
    design3: "Slate",
    design4: "Solar",
    small: "Small",
    normal: "Normal",
    medium: "Medium",
    large: "Large",
    settingsButton1: "Apply",
    settingsButton2: "Back",
    empty: "Empty",
    confirmButton1: "Back",
    confirmButton2: "Confirm",
    clearData: "Delete Data"
  }
};
